version: 0.2

phases:
  install:
    commands:
      - npm install
      - npx vite build
  build:
    commands:
      - echo Build started on `date`       

  post_build:
    commands:
      - echo Build completed on `date`
