version: 0.2

phases:
  # install:
  #   commands:
 
  # pre_build:
  #   commands:

  build:
    commands:
      - npm install
      - npx vite build 
      - echo Build started on `date`      
      - echo Logging in to Docker Hub...
      - docker login --username $username --password $password 
      - echo $AWS_ACCESS_KEY_ID
      - docker build -t crowd-simulation:v0.0.1 . AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION . --no-cache
      - docker tag crowd-simulation:v0.0.1 sarathkshatri/crowd-simulation:v0.0.1 

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push sarathkshatri/crowd-simulation:v0.0.1
