version: 0.2

phases:
  install:
    commands:
      - npm install
      - npx vite build
      
  pre_build:
    commands:
      - aws s3 sync s3://vueproject-simulation/dist/ /home/ec2-user
  build:
    commands:
      - echo Build started on `date`       

  post_build:
    commands:
      - echo Build completed on `date`
